import { applicationStages, donorTypes, opportunityStatuses } from "@/lib/fundraising";
import { saveApplication, saveDonor, saveOpportunity } from "@/app/admin/fundraising-actions";
const input="mt-2 w-full rounded-xl border border-black/10 bg-white px-4 py-3 text-sm outline-none focus:border-poem-700"; const label="text-sm font-bold text-poem-900";
const arr=(v:unknown)=>Array.isArray(v)?v.map(String).join("\n"):"";
export type Opt={id:string;label:string};
export function DonorForm({donor}:{donor?:Record<string,unknown>}){return <form action={saveDonor} className="space-y-5">{donor?.id?<input type="hidden" name="id" value={String(donor.id)}/>:null}<div className="grid gap-5 md:grid-cols-2">
<label className={label}>Donor name *<input name="name" required defaultValue={String(donor?.name??"")} className={input}/></label><label className={label}>Type<select name="donor_type" defaultValue={String(donor?.donor_type??"other")} className={input}>{donorTypes.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
<label className={label}>Country<input name="country" defaultValue={String(donor?.country??"")} className={input}/></label><label className={label}>Website<input type="url" name="website_url" defaultValue={String(donor?.website_url??"")} className={input}/></label>
<label className={label}>Contact person<input name="contact_person" defaultValue={String(donor?.contact_person??"")} className={input}/></label><label className={label}>Designation<input name="contact_title" defaultValue={String(donor?.contact_title??"")} className={input}/></label>
<label className={label}>Email<input type="email" name="contact_email" defaultValue={String(donor?.contact_email??"")} className={input}/></label><label className={label}>Phone<input name="contact_phone" defaultValue={String(donor?.contact_phone??"")} className={input}/></label>
<label className={label}>Relationship<select name="relationship_status" defaultValue={String(donor?.relationship_status??"prospect")} className={input}><option value="prospect">Prospect</option><option value="active">Active</option><option value="past">Past donor</option><option value="inactive">Inactive</option></select></label><label className={label}>Funding cycle<input name="funding_cycle" defaultValue={String(donor?.funding_cycle??"")} className={input}/></label>
<label className={label}>Funding areas<textarea name="funding_areas" rows={5} defaultValue={arr(donor?.funding_areas)} className={input}/></label><label className={label}>Preferred geographies<textarea name="preferred_geographies" rows={5} defaultValue={arr(donor?.preferred_geographies)} className={input}/></label>
<label className={label}>Preferred SDGs<textarea name="preferred_sdgs" rows={5} defaultValue={arr(donor?.preferred_sdgs)} className={input}/></label><div className="grid gap-4 sm:grid-cols-3"><label className={label}>Min grant<input name="typical_grant_min" type="number" min="0" step="0.01" defaultValue={String(donor?.typical_grant_min??"")} className={input}/></label><label className={label}>Max grant<input name="typical_grant_max" type="number" min="0" step="0.01" defaultValue={String(donor?.typical_grant_max??"")} className={input}/></label><label className={label}>Currency<input name="currency" maxLength={3} defaultValue={String(donor?.currency??"USD")} className={input}/></label></div>
</div><label className={label}>Internal notes<textarea name="notes" rows={5} defaultValue={String(donor?.notes??"")} className={input}/></label><button className="rounded-full bg-poem-950 px-6 py-3 text-sm font-extrabold text-white">{donor?.id?"Save donor":"Add donor"}</button></form>}

export function OpportunityForm({opportunity,donors}:{opportunity?:Record<string,unknown>;donors:Opt[]}){return <form action={saveOpportunity} className="space-y-5">{opportunity?.id?<input type="hidden" name="id" value={String(opportunity.id)}/>:null}<div className="grid gap-5 md:grid-cols-2">
<label className={`${label} md:col-span-2`}>Opportunity title *<input name="title" required defaultValue={String(opportunity?.title??"")} className={input}/></label><label className={label}>Donor<select name="donor_id" defaultValue={String(opportunity?.donor_id??"")} className={input}><option value="">No donor selected</option>{donors.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label><label className={label}>Funding program<input name="funding_program" defaultValue={String(opportunity?.funding_program??"")} className={input}/></label>
<label className={label}>Reference number<input name="reference_number" defaultValue={String(opportunity?.reference_number??"")} className={input}/></label><label className={label}>Source URL<input type="url" name="source_url" defaultValue={String(opportunity?.source_url??"")} className={input}/></label>
<label className={label}>Opening date<input type="date" name="opening_date" defaultValue={String(opportunity?.opening_date??"")} className={input}/></label><label className={label}>Deadline<input type="date" name="deadline" defaultValue={String(opportunity?.deadline??"")} className={input}/></label>
<label className={label}>Priority<select name="priority" defaultValue={String(opportunity?.priority??"medium")} className={input}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label className={label}>Status<select name="status" defaultValue={String(opportunity?.status??"identified")} className={input}>{opportunityStatuses.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
<label className={label}>Responsible person<input name="responsible_person" defaultValue={String(opportunity?.responsible_person??"")} className={input}/></label><label className={label}>Currency<input name="currency" maxLength={3} defaultValue={String(opportunity?.currency??"USD")} className={input}/></label>
<label className={label}>Minimum grant<input type="number" min="0" step="0.01" name="minimum_grant" defaultValue={String(opportunity?.minimum_grant??"")} className={input}/></label><label className={label}>Maximum grant<input type="number" min="0" step="0.01" name="maximum_grant" defaultValue={String(opportunity?.maximum_grant??"")} className={input}/></label>
<label className={label}>Eligible locations<textarea name="eligible_locations" rows={5} defaultValue={arr(opportunity?.eligible_locations)} className={input}/></label><label className={label}>Eligible themes<textarea name="eligible_themes" rows={5} defaultValue={arr(opportunity?.eligible_themes)} className={input}/></label><label className={label}>Relevant SDGs<textarea name="relevant_sdgs" rows={5} defaultValue={arr(opportunity?.relevant_sdgs)} className={input}/></label><label className={label}>Eligibility notes<textarea name="eligibility_notes" rows={5} defaultValue={String(opportunity?.eligibility_notes??"")} className={input}/></label>
</div><label className={label}>Internal notes<textarea name="internal_notes" rows={5} defaultValue={String(opportunity?.internal_notes??"")} className={input}/></label><button className="rounded-full bg-poem-950 px-6 py-3 text-sm font-extrabold text-white">{opportunity?.id?"Save opportunity":"Add opportunity"}</button></form>}

export function ApplicationForm({application,opportunities,donors,projects,programs}:{application?:Record<string,unknown>;opportunities:Opt[];donors:Opt[];projects:Opt[];programs:Opt[]}){return <form action={saveApplication} className="space-y-5">{application?.id?<input type="hidden" name="id" value={String(application.id)}/>:null}<div className="grid gap-5 md:grid-cols-2">
<label className={`${label} md:col-span-2`}>Application / proposal title *<input name="title" required defaultValue={String(application?.title??"")} className={input}/></label>
<label className={label}>Opportunity<select name="opportunity_id" defaultValue={String(application?.opportunity_id??"")} className={input}><option value="">No opportunity selected</option>{opportunities.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label><label className={label}>Donor<select name="donor_id" defaultValue={String(application?.donor_id??"")} className={input}><option value="">No donor selected</option>{donors.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>
<label className={label}>Project<select name="project_id" defaultValue={String(application?.project_id??"")} className={input}><option value="">No project selected</option>{projects.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label><label className={label}>Program<select name="program_id" defaultValue={String(application?.program_id??"")} className={input}><option value="">No program selected</option>{programs.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>
<label className={label}>Stage<select name="stage" defaultValue={String(application?.stage??"draft")} className={input}>{applicationStages.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label className={label}>Lead person<input name="lead_person" defaultValue={String(application?.lead_person??"")} className={input}/></label>
<label className={label}>Requested amount<input type="number" min="0" step="0.01" name="requested_amount" defaultValue={String(application?.requested_amount??"")} className={input}/></label><label className={label}>Currency<input name="currency" maxLength={3} defaultValue={String(application?.currency??"USD")} className={input}/></label>
<label className={label}>Duration (months)<input type="number" min="1" name="project_duration_months" defaultValue={String(application?.project_duration_months??"")} className={input}/></label><label className={label}>Submission deadline<input type="date" name="submission_deadline" defaultValue={String(application?.submission_deadline??"")} className={input}/></label>
<label className={label}>Submitted date<input type="date" name="submitted_at" defaultValue={String(application?.submitted_at??"")} className={input}/></label><label className={label}>Decision date<input type="date" name="decision_date" defaultValue={String(application?.decision_date??"")} className={input}/></label>
</div><label className={label}>Proposal summary<textarea name="proposal_summary" rows={5} defaultValue={String(application?.proposal_summary??"")} className={input}/></label><label className={label}>Objectives<textarea name="objectives" rows={5} defaultValue={String(application?.objectives??"")} className={input}/></label><label className={label}>Expected outcomes<textarea name="expected_outcomes" rows={5} defaultValue={String(application?.expected_outcomes??"")} className={input}/></label>
<div className="grid gap-5 md:grid-cols-2"><label className={label}>Target population<textarea name="target_population" rows={4} defaultValue={String(application?.target_population??"")} className={input}/></label><label className={label}>Geographic area<textarea name="geographic_area" rows={4} defaultValue={String(application?.geographic_area??"")} className={input}/></label></div>
<label className={label}>Relevant SDGs<textarea name="relevant_sdgs" rows={4} defaultValue={arr(application?.relevant_sdgs)} className={input}/></label><label className={label}>Decision notes<textarea name="decision_notes" rows={4} defaultValue={String(application?.decision_notes??"")} className={input}/></label><label className={label}>Internal notes<textarea name="internal_notes" rows={5} defaultValue={String(application?.internal_notes??"")} className={input}/></label><button className="rounded-full bg-poem-950 px-6 py-3 text-sm font-extrabold text-white">{application?.id?"Save application":"Create application"}</button></form>}
